name: agimed
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^0.13.6
  flame_splash_screen: ^0.1.0
  uni_links: ^0.5.1
  intl: ^0.18.1
  localstorage: ^4.0.1+2
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.10
  intl_phone_field: ^3.1.0
  image_picker: ^0.8.7+4
  file_picker: ^5.2.11
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.2.3
  flutter_inappwebview: ^5.7.2+3
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.2.1
  package_info_plus: ^4.0.2
  keep_screen_on: ^2.1.0
  share_plus: ^7.0.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  open_file_plus: ^3.4.1
  photo_view: ^0.14.0
  badges: ^3.1.1
  pinput: ^4.0.0
  animated_bottom_navigation_bar: ^1.3.3
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  readmore: ^3.0.0


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  #--------------- LOCAL ASSETS ---------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/icons/departement/


  #--------------- LOCAL FONTS ---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100


